package constants

const (
	CATEGORY_SPOT   = 0
	CATEGORY_LINEAR = 1

	ORDER_TYPE_LIMIT  = 0
	ORDER_TYPE_MARKET = 1

	ORDER_SIDE_BUY  = 0
	ORDER_SIDE_SELL = 1

	TIF_GTC       = 0
	TIF_IOC       = 1
	TIF_FOK       = 2
	TIF_POST_ONLY = 3

	ORDER_STATUS_NEW                       = 0
	ORDER_STATUS_PARTIALLY_FILLED          = 1
	ORDER_STATUS_FILLED                    = 2
	ORDER_STATUS_CANCELED                  = 3
	ORDER_STATUS_PARTIALLY_FILLED_CANCELED = 4
	ORDER_STATUS_UNTRIGGERED               = 5
	ORDER_STATUS_TRIGGERED                 = 6
	ORDER_STATUS_DEACTIVATED               = 7

	STOP_ORDER_TYPE_NORMAL      = 0
	STOP_ORDER_TYPE_STOP        = 4
	STOP_ORDER_TYPE_TP          = 5
	STOP_ORDER_TYPE_SL          = 6
	STOP_ORDER_TYPE_LIQUIDATION = 7

	MAINTENANCE_MARGIN_RATIO = 10
)
