package constants

const (
	CATEGORY_SPOT = iota
	CATEGORY_LINEAR

	ORDER_TYPE_LIMIT
	ORDER_TYPE_MARKET

	ORDER_SIDE_BUY
	ORDER_SIDE_SELL

	TIF_GTC
	TIF_IOC
	TIF_FOK
	TIF_POST_ONLY

	ORDER_STATUS_NEW
	ORDER_STATUS_PARTIALLY_FILLED
	ORDER_STATUS_FILLED
	ORDER_STATUS_CANCELED
	ORDER_STATUS_PARTIALLY_FILLED_CANCELED
	ORDER_STATUS_UNTRIGGERED
	ORDER_STATUS_TRIGGERED
	ORDER_STATUS_DEACTIVATED

	BUCKET_AVAILABLE
	BUCKET_LOCKED
	BUCKET_MARGIN

	STOP_ORDER_TYPE_NORMAL = iota
	STOP_ORDER_TYPE_STOP
	STOP_ORDER_TYPE_TP
	STOP_ORDER_TYPE_SL
	STOP_ORDER_TYPE_LIQUIDATION
)
